version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - mern-app
  
  
  
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes: 
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 5000:5000
    networks:
      - mern-app
    depends_on:
      - mongo
      - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /frontend/node_modules
    networks:
      - mern-app
    ports:
      - 5173:5173
    command: npm run dev -- --host
    depends_on:
      - api

volumes:
  mongo_data:
  redis_data:
networks:
  mern-app:
    driver: bridge