services:
  - type: web
    name: frontend
    env: docker
    region: oregon
    plan: free
    branch: main
  
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /
    
    # routes:
    #   - type: rewrite
    #     source: /*
    #     destination: /

  - type: web
    name: backend
    env: docker
    region: oregon
    plan: free
    branch: main

    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /
   
   
  - type: keyvalue
    name: bullmq
    ipAllowList: # Allow external connections from everywhere
    - source: 0.0.0.0/0
      description: everywhere
databases:
  - name: mongo
    region: oregon
    plan: free

