services:
  - type: web
    name: frontend
    env: docker
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start -- --host
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      key: NODE_ENV
      value: production
    autoDeploy: true
    healthCheckPath: /
    ports:
      - 5173
    routes:
      type: rewrite
      source: /*
      destination: /

  - type: web
    name: backend
    env: docker
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      key: NODE_ENV
      value: production
    autoDeploy: true
    healthCheckPath: /
    ports:
      - 5000
    dependsOn:
      - name: mongo
        type: database
      - name: bullmq
        type: keyvalue
  - type: keyvalue
    name: bullmq
    ipAllowList: # Allow external connections from everywhere
    - source: 0.0.0.0/0
      description: everywhere
databases:
  - name: mongo
    region: oregon
    plan: free

